### ISSUE TITLE
Startup macine stats

### ISSUE THREAD

**Issue by RoTorEx** [catppuccin/iterm#16]
How to display statistics on the computer with a picture when starting the terminal as in the picture below?

[image](https://github.com/catppuccin/iterm/assets/78344396/322278ac-530f-413d-a6d1-604d8bbeaf58)

**Comment by achan1912** [comment]
I believe it is done by modifying the .zshenv or .zshrc files. 

The fetch tool was mentioned here: https://github.com/catppuccin/iterm/issues/12
