### ISSUE TITLE
Contrast in frappe in some tools

### ISSUE THREAD

**Issue by KervyN** [catppuccin/iterm#17]
Hi,

i really enjoy this theme, but I have a hard time to read some text.

1st image is rubys `irb` shell
2nd image is the "daemon restart" dialog after `apt install ...`

Is there a good way to improve this? What I've found is to raise the minimum contrast in iterm to 30 (3rd screenshot). Is there something better?

![image](https://github.com/catppuccin/iterm/assets/1584820/8c15658d-ff4c-47e3-9d16-2bd56752929d)
![image](https://github.com/catppuccin/iterm/assets/1584820/bbd44bd7-27ee-46c5-881d-760fdc2bbb8f)
![image](https://github.com/catppuccin/iterm/assets/1584820/642d7029-29c2-4d04-823b-370ac14c2e30)

**Comment by nekowinston** [comment]
Upstream -> https://github.com/catppuccin/catppuccin/issues/1961
