### ISSUE TITLE
Why normal black = bright white?

### ISSUE THREAD

**Issue by krisantuswanandi** [catppuccin/iterm#19]
Is it expected to have normal black (ansi 0) the same color with bright white (ansi 15) and why is that?

<img width="220" alt="image" src="https://github.com/catppuccin/iterm/assets/11497316/d7760449-1131-4235-838f-11c45292b684">

I'm currently working with https://github.com/rivo/tview and the hello world example shows nothing in this theme.

<img width="500" alt="image" src="https://github.com/catppuccin/iterm/assets/11497316/8a5e829e-b284-437d-b78b-33627627e36a">

This is after I change the bright white (ansi 15) to follow the normal white (ansi 7)

<img width="500" alt="image" src="https://github.com/catppuccin/iterm/assets/11497316/8f3d0ecd-dda7-4d47-bebc-c01c0c87d63e">

**Comment by unseen-ninja** [comment]
> Is it expected to have normal black (ansi 0) the same color with bright white (ansi 15) and why is that?

It def. isn't expected and hence is a huge oversight on our end. We're currently in the progress of adapting palette colours to be better suitable with the ANSI standards and thus prevent issues like this from happening. We're hoping to release this accross terminals soon.
