### ISSUE TITLE
Feature requests, cappuccino icon theme for iterm2

### ISSUE THREAD

**Issue by FrancoTampieri** [catppuccin/iterm#25]
Hi this is a feature request.

I would like have the catppuccing icon themes for iterm2, for example to show the icons on the top with that theme, and not with the standard one like that:

<img width="1248" alt="Screenshot 2024-09-14 alle 14 00 50" src="https://github.com/user-attachments/assets/95f347ee-ddb2-4429-91f4-893efcab5ad5">

**Comment by uncenter** [comment]
I don't believe those are able to be themed.

**Comment by sgoudham** [comment]
Closing as not planned for now but feel free to re-open if you find any documentation on your feature request being possible, thanks!
