### ISSUE TITLE
iTerm2-Color-Schemes Repository

### ISSUE THREAD

**Issue by justTOBBI** [catppuccin/iterm#8]
After looking into Windows terminal themes and seeing that they port the themes over from https://github.com/mbadolato/iTerm2-Color-Schemes, I think it would be a good idea to add catppuccin themes in there.
Let me know if that's a good idea or not :)

**Comment by spookyintheam** [comment]
This seems like a nice idea, yes. Are you on macOS?

**Comment by justTOBBI** [comment]
Any update on this @ghostx31?
I'm not on MacOS

**Comment by spookyintheam** [comment]
I'm sorry, no. This requires macOS and I don't have a device running macOS. Tagging in @nekowinston who can sort this out.

**Comment by clach04** [comment]
Added in https://github.com/mbadolato/iTerm2-Color-Schemes/commit/1e29958741314147be5c1035c51511104b203c5e

**Comment by clach04** [comment]
> I'm sorry, no. This requires macOS and I don't have a device running macOS. Tagging in @nekowinston who can sort this out.

It looks like the tool chain is pure python and doesn't need an Apple device (not had chance to test build myself yet).

**Comment by clach04** [comment]
@justTOBBI you can pull windows terminal config from that same repo you referenced, how does it look? I can confirm the Putty settings for Catppuccin Macchiato work great.

**Comment by justTOBBI** [comment]
Thanks for the hint, seems to be workin :)
